#+ endpoint: http://live.dbpedia.org/sparql

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
SELECT ?city ?population
WHERE {
 ?city dbp:areaCode	"010"^^xsd:string ;
 	dbo:populationTotal ?population .
  FILTER (?population > 500000)
}
