#+ endpoint: http://live.dbpedia.org/sparql

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
SELECT ?city ?population
WHERE {
 ?city dbo:areaCode	"020"^^xsd:string ;
 	dbo:populationTotal ?population .
} ORDER BY DESC (?population)
LIMIT 5
