#+ endpoint: http://live.dbpedia.org/sparql

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?city ?label
WHERE {
 ?city dbo:areaCode	"020"^^xsd:string ;
 	rdfs:label ?label .
  FILTER (lang(?label) = "en")
}
