#+ endpoint: http://live.dbpedia.org/sparql

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
ASK {
	dbpedia:Amsterdam dbo:areaCode	"020"^^xsd:string .
}
