#+ endpoint: http://live.dbpedia.org/sparql

PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
SELECT ?g
WHERE {
  GRAPH ?g {
    dbpedia:Amsterdam dbo:areaCode [] .
  }
}
